name: test_workflow
on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: setup Node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '18'

      - name: install deps
        run: npm ci

      - name: build
        run: npm run build
